name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  CLUSTER_RESOURCE_GROUP: mouismail
  STAGING_CLUSTER: mouismail-test
  PRODUCTION_CLUSTER: mouismail-test
  STAGING_NAMESPACE: sap-staging
  PRODUCTION_NAMESPACE: sap-prod
  STAGING_SECRET: avf-secret

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy-to-staging:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install and configure Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/aks-set-context@v1
        with:
          creds:  ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ env.STAGING_CLUSTER }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

      - uses: azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{env.IMAGE_NAME}}
          container-registry-username: ${{ github.actor }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          secret-name: ${{ env.STAGING_SECRET }}
          namespace: ${{ env.STAGING_NAMESPACE }}

      # - name: Set current Kubernetes context to staging cluster
      #   run: az aks get-credentials --resource-group mouimsail --name ${{ env.STAGING_CLUSTER }}

      - name: Deploy to staging
        run: kubectl apply -f k8s/staging -n ${{ env.STAGING_NAMESPACE }}

  deploy-to-production:
    needs: deploy-to-staging
    environment:
      name: Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install and configure Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set current Kubernetes context to production cluster
        run: az aks get-credentials --resource-group mouimsail --name ${{ env.PRODUCTION_CLUSTER }}

      - name: Deploy to production
        run: kubectl apply -f k8s/production -n ${{ env.PRODUCTION_NAMESPACE }}
